name: PHP Extension CI

on:
  push:
    branches: [ CI ]
  pull_request:
    branches: [ CI ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.2', '8.3']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, intl, gd, exif, iconv
        coverage: none

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf build-essential

    - name: Build PHP extension
      run: |
        phpize
        ./configure
        make

    - name: Run tests
      run: make test TESTS="-q --show-diff"

    - name: Check for memory leaks
      run: make test TESTS="-m"