name: PHP Extension CI

on:
  push:
    branches: [ CI ]
  pull_request:
    branches: [ CI ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3', '8.4']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y  build-essential autoconf automake bison flex re2c gdb libtool make pkgconf valgrind git libxml2-dev libsqlite3-dev

    - name: Build PHP extension
      run: |
        phpize
        ./configure
        make

    - name: Run tests
      run: make test TESTS="-q --show-diff"

    - name: Check for memory leaks
      run: make test TESTS="-m"